# Generated by Django 4.1.4 on 2023-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artesano',
            name='release_date',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre_departamento',
            field=models.CharField(max_length=30, null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='act_hora',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='act_usua',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Usuario que Registra'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
