# Generated by Django 4.1.4 on 2023-06-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_vigencia_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='referencia',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Referencia Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor_compra',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor_venta',
            field=models.IntegerField(null=True),
        ),
    ]
