# Generated by Django 4.1.4 on 2023-06-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_referencia_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod_prod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualiza',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor_compra',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor_venta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Valor de venta'),
        ),
    ]
